// <auto-generated />
using System;
using GestionDocumental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDocumental.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250304120648_UpdateDocumento")]
    partial class UpdateDocumento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDocumental.Core.Entities.Documento", b =>
                {
                    b.Property<int>("ID_Documento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Documento"));

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Modificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Subida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Validacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Firma_Electronica")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Formato_Descargable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formato_Imprimible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hash_Integridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Tipo_Documento")
                        .HasColumnType("int");

                    b.Property<int>("ID_UsuarioModificador")
                        .HasColumnType("int");

                    b.Property<int>("ID_UsuarioOrigen")
                        .HasColumnType("int");

                    b.Property<bool>("Necesita_Actualizar_Index")
                        .HasColumnType("bit");

                    b.Property<float>("Relevancia")
                        .HasColumnType("real");

                    b.Property<string>("Ruta_Archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Ultima_Indexacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Validado")
                        .HasColumnType("bit");

                    b.HasKey("ID_Documento");

                    b.ToTable("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
